### ISSUE TITLE
ADV180012 | Microsoft Guidance for Speculative Store Bypass

### ISSUE THREAD

**Issue by rychannel** [timidri/puppet-meltdown#13]
Another Spectre-like vulnerability has been reported.  No updates yet on how to detect or mitigate.

Just want to make sure its on your radar. https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/ADV180012#ID0EMGAC

**Comment by kreeuwijk** [comment]
Thanks, we will track and update as mitigation becomes available.
