### ISSUE TITLE
Acceptance tests failing on win-2008[r2]-x86_64

### ISSUE THREAD

**Issue by timidri** [timidri/puppet-meltdown#23]
When running the new acceptance tests (see https://github.com/timidri/puppet-meltdown/pull/22) the following error is displayed: 
```
On host `r19aw4fc56ukq3q.delivery.puppetlabs.net'
Failure/Error: result = run_shell(command)
RuntimeError:
  shell failed
  `$env:FACTERLIB="$(puppet config print environmentpath)/production/modules/meltdown/lib/facter"; facter -p --json meltdown`
  ======
  [{"node"=>"r19aw4fc56ukq3q.delivery.puppetlabs.net", "target"=>"r19aw4fc56ukq3q.delivery.puppetlabs.net", "action"=>"command", "object"=>"$env:FACTERLIB=\"$(puppet config print environmentpath)/production/modules/meltdown/lib/facter\"; facter -p --json meltdown", "status"=>"failure", "result"=>{"stdout"=>"{\r\n  \"meltdown\": \"\"\r\n}\r\n", "stderr"=>"facter.bat : 2019-09-20 12:56:30.669985 ERROR puppetlabs.facter - error while resolving custom fact \"meltdown\": 765: unexpected token at ''\n    + CategoryInfo          : NotSpecified: (2019-09-20 12:5...ted token at '':String) [], RemoteException\n    + FullyQualifiedErrorId : NativeCommandError\n", "exit_code"=>1, "_error"=>{"kind"=>"puppetlabs.tasks/command-error", "issue_code"=>"COMMAND_ERROR", "msg"=>"The command failed with exit code 1", "details"=>{"exit_code"=>1}}}}]
```
Reproducing on the machine itself:

![image](https://user-images.githubusercontent.com/1586813/65341273-404d5080-dbd0-11e9-8620-eb2a083df14e.png)

Should we support win2008? If not, we need to remove it from metadata as supported OS.

**Comment by kreeuwijk** [comment]
We do support Win2008/R2, checking why this is failing.

**Comment by kreeuwijk** [comment]
Confirmed the test fails on Windows 2008/R2 RTM due to Powershell 2.0:
- The SpeculationControl module can't be loaded in this old Powershell version
- The ConvertTo-Json command does not exist in Powershell 2.0

Now updating the SP1 and Powershell 3.0 to verify it does work in that scenario.

**Comment by kreeuwijk** [comment]
Updated lib/meltdown/spectre-meltdown-checker.ps1 so it now correctly handles situations with Powershell 2.0
