### ISSUE TITLE
Replace absolute path with relative

### ISSUE THREAD

**Issue by timidri** [timidri/puppet-meltdown#4]
https://github.com/timidri/puppet-meltdown/blob/4e8d02c6494c0433be747ef70d4714d0e7a83cae/lib/facter/meltdown_win.rb#L9

See https://github.com/timidri/puppet-meltdown/blob/4e8d02c6494c0433be747ef70d4714d0e7a83cae/lib/facter/meltdown.rb#L62 for possible solution.

**Comment by kreeuwijk** [comment]
Fixed in release 0.9.1
